### ISSUE TITLE
request for new Hackage release

### ISSUE THREAD

**Issue by peterbecich** [linear-generics/linear-generics#16]
Can we make a new Hackage release with the new `template-haskell` upper bound?
https://github.com/linear-generics/linear-generics/commit/6434ca1070e3e5e31981072dd9ecbfdc03bc0ff5

https://hackage.haskell.org/package/linear-generics

Thank you

**Comment by treeowl** [comment]
Yes, totally. If I haven't done it by Tuesday, please ping me again.

**Comment by treeowl** [comment]
All done! [`linear-generics-0.2.1`](https://hackage.haskell.org/package/linear-generics-0.2.1) is on Hackage. Please test!

**Comment by peterbecich** [comment]
thanks, I'll test it later

**Comment by andreasabel** [comment]
Unfortunately, the recent release is already outdated; I guess a new release (or potentially a revision) is needed for GHC 9.6.1:
- #19

**Comment by treeowl** [comment]
@andreasabel Your request for a new release has been granted—it is now on Hackage. I don't know if I'll go to the trouble of validating a Hackage revision for the previous version; probably not.
